<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">System Tools - ACL</h3>
            </div>
            <div class="panel-body">
                <p>Here you can set permissions for user roles to application routes.</p>                
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h3 class="panel-title">Routes</h3>
            </div>            
            <ul class="list-group">
                <?php foreach($this->routes as $route){?>
                <li><?php echo $route; ?></li>
               <?php }?>
             </ul>
            
          
        </div>
    </div>
    
</div>
<?php 
if(is_array($this->messages)){ 
    $messageBody = '';
    foreach($this->messages as $message){
        $messageBody .= '<p>'.$message.'</p>';
    }  
?>
<script>
    $('#myModalLabel').html('System Message');
    $('#myModal .modal-body').html('<?php echo $messageBody;?>');
    $('#myModal').modal('show');
</script>
<?php }?>

