<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">System Tools</h3>
            </div>
            <div class="panel-body">
                <p>The Onyx System is build up with a collection of modules. Some are dependent on each other so installation via composer is the best method.</p>
                <p><a href="https://getcomposer.org/" target="_blank">https://getcomposer.org/</a></p>
                <h4>Module List</h4>
                <ul>
                <?php foreach($this->repoList as $repo){ ?>
                    <li><a href="<?php echo $repo['url']; ?>" target="_blank"><?php echo $repo['name']; ?></a></li>
                <?php } ?>
                </ul>    
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h3 class="panel-title">Database Tables Setup</h3>
            </div>            
            <ul class="list-group">
                <?php foreach($this->repoList as $repo){ ?>
                    <li class="list-group-item list-group-item-info"><?php echo $repo['name']; ?><span class="badge"><a href="/system/setup/<?php echo $repo['name']; ?>">Create default table(s)</a></span></li>
                <?php } ?>
             </ul>
          
        </div>
    </div>
    
</div>
<?php 
if(is_array($this->messages)){ 
    $messageBody = '';
    foreach($this->messages as $message){
        $messageBody .= '<p>'.$message.'</p>';
    }  
?>
<script>
    $('#myModalLabel').html('System Message');
    $('#myModal .modal-body').html('<?php echo $messageBody;?>');
    $('#myModal').modal('show');
</script>
<?php }?>

